### ISSUE TITLE
Cannot Download HW3 Data

### ISSUE THREAD

**Issue by TATOAO** [virginiakm1988/ML2022-Spring#2]
What I have done:

1. fork the project
2. git clone by http
3. git lfs fetch 

It raise this issue:

❯ git lfs fetch
fetch: Fetching reference refs/heads/main
batch response: This repository is over its data quota. Account responsible for LFS bandwidth should purchase more data packs to restore access.
error: failed to fetch some objects from 'https://github.com/TATOAO/ML2022-Spring.git/info/lfs'

what is the correct way to download the data?

Thank you in advance

**Comment by TATOAO** [comment]
The same issue occurs when I clone the original project directly.

❯ cd ML2022-Spring
❯ git lfs fetch
fetch: Fetching reference refs/heads/main
batch response: This repository is over its data quota. Account responsible for LFS bandwidth should purchase more data packs to restore access.                                      
error: failed to fetch some objects from 'https://github.com/virginiakm1988/ML2022-Spring.git/info/lfs'

**Comment by virginiakm1988** [comment]
Hi, 
You can download the data using the command
`! wget -O food11.zip "https://github.com/virginiakm1988/ML2022-Spring/blob/main/HW03/food11.zip?raw=true"`

**Comment by TATOAO** [comment]
> Hi, You can download the data using the command `! wget -O food11.zip "https://github.com/virginiakm1988/ML2022-Spring/blob/main/HW03/food11.zip?raw=true"`

Thanks for your reply.

I have run the command in terminal. But it turns out the zip file still has an incorrect size (135 bytes).

**Comment by TATOAO** [comment]
And I check the command in the notebook:
`! wget https://www.dropbox.com/s/6l2vcvxl54b0b6w/food11.zip`

it's no longer available as well.

**Comment by virginiakm1988** [comment]
Hi, 

Sorry for the inconvenience.  
You can download the data here instead.
https://www.kaggle.com/competitions/ml2022spring-hw3b/data

**Comment by TATOAO** [comment]
Thank you! The problem is solved.
